version: '3'

services:
  www:
    image: wordpress:latest
    container_name: ${ALIAS}-www
    restart: always
    logging:
      # Configure logs retention
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - ./.env
    environment:
      # Connect WordPress to the database
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      VIRTUAL_HOST: ${HOST}
    volumes:
      # Make the content of WordPress visible for changes
      - ./www:/var/www/html
    networks:
      - proxy
      - internal
    depends_on:
      - db
    labels:
      # HTTP to HTTPS redirection and middleware assignment
      - traefik.enable=true
      - traefik.http.routers.${ALIAS}-http.entrypoints=http
      - traefik.http.routers.${ALIAS}-http.rule=Host(`${HOST}`)
      - traefik.http.routers.${ALIAS}-http.middlewares=${ALIAS}-to-https,${ALIAS}-headers

      # HTTPS routing and TLS configuration
      - traefik.http.routers.${ALIAS}.entrypoints=https
      - traefik.http.routers.${ALIAS}.rule=Host(`${HOST}`)
      - traefik.http.routers.${ALIAS}.tls=true
      - traefik.http.routers.${ALIAS}.tls.certresolver=letsencrypt

      # Middleware for redirecting HTTP to HTTPS
      - traefik.http.middlewares.${ALIAS}-to-https.redirectscheme.scheme=https

      # Header middleware configuration
      - traefik.http.routers.${ALIAS}.middlewares=${ALIAS}-headers

      # Security headers configuration
      - traefik.http.middlewares.${ALIAS}-headers.headers.browserXSSFilter=true
      - traefik.http.middlewares.${ALIAS}-headers.headers.contentTypeNosniff=true
      - traefik.http.middlewares.${ALIAS}-headers.headers.frameDeny=true
      - traefik.http.middlewares.${ALIAS}-headers.headers.referrerPolicy=no-referrer
      - traefik.http.middlewares.${ALIAS}-headers.headers.customFrameOptionsValue=SAMEORIGIN

      # Strict Transport Security (HSTS) configuration
      - traefik.http.middlewares.${ALIAS}-headers.headers.stsSeconds=15552000
      - traefik.http.middlewares.${ALIAS}-headers.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.${ALIAS}-headers.headers.stsPreload=true
      - traefik.http.middlewares.${ALIAS}-headers.headers.forceSTSHeader=true

  db:
    image: mysql:5.7
    container_name: ${ALIAS}-db
    restart: always
    logging:
      # Configure the logs retention
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - ./.env
    environment:
      # Set database credentials
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      # Store it as a local directory (my personal preference)
      - ./db:/var/lib/mysql
    networks:
      - internal

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: ${ALIAS}-pma
    networks:
      - internal
      - proxy
    depends_on:
      - db
    restart: unless-stopped
    logging:
      # Configure the logs retention
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - ./.env
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - UPLOAD_LIMIT=300M
    labels:
      # HTTP to HTTPS redirection and middleware assignment
      - traefik.enable=true
      - traefik.http.routers.pma-http.entrypoints=http
      - traefik.http.routers.pma-http.rule=Host(`${PHPMYADMIN_DOMAIN}`)
      - traefik.http.routers.pma-http.middlewares=pma-to-https,pma-headers

      # HTTPS routing and TLS configuration
      - traefik.http.routers.phpmyadmin.entrypoints=https
      - traefik.http.routers.phpmyadmin.rule=Host(`${PHPMYADMIN_DOMAIN}`)
      - traefik.http.routers.phpmyadmin.tls=true
      - traefik.http.routers.phpmyadmin.tls.certresolver=letsencrypt

      # Middleware for redirecting HTTP to HTTPS
      - traefik.http.middlewares.pma-to-https.redirectscheme.scheme=https

      # Header middleware configuration
      - traefik.http.routers.phpmyadmin.middlewares=pma-headers

      # Security headers configuration
      - traefik.http.middlewares.pma-headers.headers.browserXSSFilter=true
      - traefik.http.middlewares.pma-headers.headers.contentTypeNosniff=true
      - traefik.http.middlewares.pma-headers.headers.frameDeny=true
      - traefik.http.middlewares.pma-headers.headers.referrerPolicy=no-referrer
      - traefik.http.middlewares.pma-headers.headers.customFrameOptionsValue=SAMEORIGIN

      # Strict Transport Security (HSTS) configuration
      - traefik.http.middlewares.pma-headers.headers.stsSeconds=15552000
      - traefik.http.middlewares.pma-headers.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.pma-headers.headers.stsPreload=true
      - traefik.http.middlewares.pma-headers.headers.forceSTSHeader=true      

  redis:
    image: redis:alpine
    container_name: ${ALIAS}-redis
    networks:
      - internal    
    ports:
      - 6379:6379
    entrypoint: redis-server --appendonly yes

networks:
  # Assuming `proxy` is Traefik network name
  proxy:
    external: true
  internal:
    external: false